name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen? And please provide any relevant error messages or logs.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: App Version
      description: Version can be found at the bottom right corner of the app screen.
    validations:
      required: false