[features]
seeds = false

[workspace]
members = [
    "programs/bettercallsol",
]

[programs.localnet]
bettercallsol = "HCcwD495j265Vqunp55pS8z64ddt9FnoswnBi61FH22S"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = ".key/localhost.json"

[scripts]
test = "ts-mocha -p tsconfig.json -t 1000000 tests/*.ts"
